name: CI

on: [push]

env:
  POETRY_HOME: /opt/poetry

jobs:
    build:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                python-version: ["3.11", "3.12"]
        steps:
            - name: Check out source code
              uses: actions/checkout@v4

            - name: Set up Python
              uses: actions/setup-python@v5
              with:
                  python-version: ${{ matrix.python-version }}
                  cache: poetry

            - name: Install poetry
              run: |
                python3 -m venv $POETRY_HOME &&
                $POETRY_HOME/bin/pip install poetry

            - name: Install dependencies
              run: $POETRY_HOME/bin/poetry install --with dev

            - name: Run linters
              run: $POETRY_HOME/bin/poetry run pre-commit run all-files

            - name: Run tests
              run: $POETRY_HOME/bin/poetry run pytest
